# Generated by Django 6.1 on 2026-08-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Жоба атауы')),
                ('category', models.CharField(choices=[('advertising', 'Жарнама'), ('print', 'Баспа'), ('design', 'Дизайн'), ('outdoor', 'Сыртқы жарнама')], default='advertising', max_length=30, verbose_name='Санат')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Негізгі сурет')),
                ('year', models.PositiveIntegerField(default=2026, verbose_name='Жыл')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Таңдаулы жоба')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
            options={
                'verbose_name': 'Жоба',
                'verbose_name_plural': 'Жобалар',
                'ordering': ['-created_at'],
            },
        ),
    ]
