# Generated by Django 6.1 on 2026-08-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Қызмет атауы')),
                ('short_title', models.CharField(blank=True, max_length=100, verbose_name='Қысқа атауы')),
                ('description', models.TextField(verbose_name='Сипаттама')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Сурет')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Реттік нөмір')),
                ('is_active', models.BooleanField(default=True, verbose_name='Белсенді')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
            options={
                'verbose_name': 'Қызмет',
                'verbose_name_plural': 'Қызметтер',
                'ordering': ['number', 'created_at'],
            },
        ),
    ]
