# Generated by Django 6.1 on 2026-08-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True, verbose_name='Толық сипаттама'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='URL атауы'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Қысқаша сипаттама'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Негізгі сурет'),
        ),
    ]
