# Generated by Django 6.1 on 2026-08-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service_full_description_service_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL атауы'),
        ),
    ]
