# Generated by Django 6.1 on 2026-08-30 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='Сурет')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Сурет атауы')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Реттік нөмір')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='main.service', verbose_name='Қызмет')),
            ],
            options={
                'verbose_name': 'Галерея суреті',
                'verbose_name_plural': 'Галерея суреттері',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
