# Generated by Django 6.1 on 2026-08-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_serviceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Аты-жөні')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Хабарлама')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Өңделді')),
            ],
            options={
                'verbose_name': 'Өтінім',
                'verbose_name_plural': 'Өтінімдер',
                'ordering': ['-created_at'],
            },
        ),
    ]
